Repository apptrackit/trackit-backend, pull requests merged in 2025-05, with the labels that each got.

#6 Admin panel + session token
  .gitignore
  README.md
  app.js
  auth.js
  controllers/adminController.js
  controllers/authController.js
  database.js
  package-lock.json
  package.json
  public/admin-dashboard.html
  public/css/admin-dashboard.css
  public/css/index.css
  public/index.html
  public/scripts/admin-dashboard.js
  public/scripts/clipboard-helper.js
  public/scripts/index.js
  routes/admin.js
  routes/auth.js
  routes/users.js
Labels: bug, enhancement

#14 fix: maintain existing user data on whitespace input in admin dashboard
  public/scripts/admin-dashboard.js
Labels: bug

#23 Big Admin dashboard+api update
  README.md
  auth.js
  controllers/adminController.js
  controllers/authController.js
  controllers/userController.js
  database.js
  public/admin-dashboard.html
  public/css/admin-dashboard.css
  public/css/index.css
  public/scripts/admin-dashboard.js
  public/scripts/index.js
  routes/admin.js
  routes/auth.js
Labels: enhancement
